{
  "swagger" : "2.0",
  "info" : {
    "description" : "API A is called by consumer directly and it will call API B and API C to get data",
    "version" : "1.0.0",
    "title" : "API A for microservices demo",
    "contact" : {
      "email" : "stevehu@gmail.com"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host" : "a.networknt.com",
  "basePath" : "/apid",
  "schemes" : [ "http" ],
  "paths" : {
    "/data1" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data10" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data11" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data12" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data13" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data14" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data15" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data16" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data17" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data18" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data19" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data2" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data20" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data21" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data22" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data23" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data24" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data25" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data3" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data4" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data5" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data6" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data7" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data8" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/data9" : {
      "get" : {
        "description" : "Return an array of strings collected from down stream APIs",
        "operationId" : "listData",
        "security" : [ {
          "a_auth" : [ "api_a.w", "api_a.r" ]
        } ],
        "x-accepts" : "application/json",
        "x-contentType" : "application/json"
      }
    },
    "/server/info" : {
      "get" : {
        "security" : [ {
          "a_auth" : [ "server.info.r" ]
        } ]
      }
    }
  },
  "securityDefinitions" : {
    "a_auth" : {
      "type" : "oauth2",
      "authorizationUrl" : "http://localhost:8080/oauth2/code",
      "flow" : "implicit",
      "scopes" : {
        "api_a.w" : "write access",
        "api_a.r" : "read access",
        "server.info.r" : "read server info"
      }
    }
  }
}